apiVersion: v1
kind: ConfigMap
metadata:
  name: service-primes-config
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/primes"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "12345"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-primes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-primes
  template:
    metadata:
      labels:
        app: service-primes
    spec:
      containers:
      - name: service-primes
        image: service-primes:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: service-primes-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: service-primes-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: service-primes-config
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: service-primes-config
              key: SPRING_RABBITMQ_HOST
        - name: SPRING_RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: service-primes-config
              key: SPRING_RABBITMQ_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: service-primes
spec:
  selector:
    app: service-primes
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
